// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/wajox/krakend-proxy/internal/app/dependencies"
	"github.com/wajox/krakend-proxy/internal/app/initializers"
)

// Injectors from wire.go:

func BuildApplication() (*Application, error) {
	serviceConfig, err := initializers.InitializeConfig()
	if err != nil {
		return nil, err
	}
	logger, err := initializers.InitializeLogger()
	if err != nil {
		return nil, err
	}
	container := &dependencies.Container{
		Cfg:    serviceConfig,
		Logger: logger,
	}
	application := &Application{
		Container: container,
	}
	return application, nil
}
